

listener {
timeout = 500
on-timeout = hyprlock
}
# Listener für das Zuklappen des Deckels
listener {
    timeout = 0
    on-suspend = hyprlock                        # Sperrt den Bildschirm sofort, wenn der Suspend-Modus durch Deckel-Zuklappen ausgelöst wird
}


