+ add speed 0.1
- add speed -0.1
= set speed 1.0

# Arrow Config
LEFT seek -5
RIGHT seek 5
UP add volume 2
DOWN add volume -2

# Vim Config
h seek -5
l seek 5
k add volume 2
j add volume -2

# Playlist navigation
n playlist-next
p playlist-prev

t script-message osc-show
T script-message osc-hide

