-- #######################################################################################
-- Übersetzt aus hyprland.conf nach hyprland.lua (neue Lua-Konfigurationssprache von Hyprland)
-- Diese Datei gehört nach ~/.config/hypr/hyprland.lua
-- Hyprland muss danach neu gestartet werden, damit die Lua-Config statt der .conf greift.
-- Refer to the wiki for more information: https://wiki.hypr.land/Configuring/Start/
-- #######################################################################################
-- HINWEIS: Der alte "AUTOGENERATED"-Warnhinweis + "autogenerated = 0" aus der .conf hat
-- in der Lua-Welt keine Entsprechung und wurde daher weggelassen.

------------------
---- MONITORE ----
------------------
-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({ output = "",       mode = "preferred",       position = "auto",    scale = 1.0 })
hl.monitor({ output = "DP-3",     mode = "1920x1080@144",   position = "1920x0", scale = 1.2 })
hl.monitor({ output = "HDMI-A-4", mode = "3840x2160@60",    position = "0x0",    scale = 2 })

-- Zwingt Workspace 1 auf den Samsung (HDMI-A-4)
-- default = true sorgt dafür, dass Hyprland beim Start diesen Monitor fokussiert
hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-4", default = true })
hl.workspace_rule({ workspace = "5", monitor = "DP-3",     default = true })

-- unscale XWayland
hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

---------------------
---- MY PROGRAMS ----
---------------------
-- - waybar
-- - wofi
-- - hyprlock
-- - hyprshot
-- - hyprpaper
-- - hypridle
-- - swaync
local browser     = "app.zen_browser.zen"
local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "wofi --show drun --insensitive"

-------------------
---- AUTOSTART ----
-------------------
-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
-- HINWEIS: In der .conf standen zwei "exec-once"-Blöcke an unterschiedlichen Stellen
-- (oben unter AUTOSTART, und weiter unten kurz vor den Fensterregeln). Für Autostart
-- spielt die Reihenfolge im File keine Rolle, deshalb hier zu einem Block zusammengefasst.
hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("waybar & hyprpaper & swaync & hypridle &")
    hl.exec_cmd("sleep 1 && $HOME/.config/wallpaper/script/Random_Wallpaper.sh")

    -- Startet cliphist für Text
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    -- Startet cliphist für Bilder
    hl.exec_cmd("wl-paste --type image --watch cliphist store")

    -- (ehemals weiter unten im File, siehe "WINDOWS AND WORKSPACES")
    hl.exec_cmd("sh -c 'command -v synology-drive >/dev/null 2>&1 && synology-drive'")
    hl.exec_cmd("sleep 2 && xrandr --output HDMI-A-4 --primary")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRSHOT_DIR", "/home/tobi/Pictures/Screenshots")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
-- ODER (falls du qt6 nutzt, was bei neuerem Dolphin der Fall ist):
-- HINWEIS: das war in deiner .conf schon so (zweimal gesetzt) - der zweite Aufruf
-- überschreibt den ersten, es "gewinnt" also qt6ct. Wenn das nicht gewollt ist,
-- eine der beiden Zeilen löschen.
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-----------------------
---- LOOK AND FEEL ----
-----------------------
-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 0,
        gaps_out = 0,
        border_size = 1,
        col = {
            active_border   = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "master",
    },
    decoration = {
        rounding       = 10,
        rounding_power = 2,
        active_opacity   = 1.0,
        inactive_opacity = 1.0,
        -- shadow = {
        --     enabled      = true,
        --     range        = 4,
        --     render_power = 3,
        --     color        = 0xee1a1a1a, -- Achtung: Format ist hier 0xAARRGGBB, nicht rgba(...)
        -- },
        -- blur = {
        --     enabled  = true,
        --     size     = 3,
        --     passes   = 1,
        --     vibrancy = 0.1696,
        -- },
    },
    animations = {
        -- war in deiner .conf "enabled = false, please :)" -> einfach false
        enabled = false,
    },
})

-- Beziers/Animations bleiben unten definiert, greifen aber nicht solange
-- animations.enabled = false oben gesetzt ist. Praktisch, falls du sie später
-- wieder aktivierst.
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}   } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}   } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}      } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1.0} } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}    } })

hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only" - bei dir auskommentiert, hier die Lua-Entsprechung:
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        -- pseudotile = true, -- Master switch for pseudotiling, gebunden an mainMod + P (siehe Keybinds)
        preserve_split = true,
        force_split    = 2,     -- Split new window to the right
        smart_split    = false, -- Splits according to the cursor
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        -- 'master': Das neue Fenster wird zum Hauptfenster (Master).
        -- Das bisherige Master-Fenster rutscht automatisch in den Stack.
        new_status = "master",
        -- Stellt sicher, dass der Master links bleibt und der Stack rechts
        orientation = "left",
        -- Wie viel Platz der Master einnimmt (0.5 = 50%)
        mfact = 0.5,
    },
})

----------------
----  MISC  ----
----------------
hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})

---------------
---- INPUT ----
---------------
hl.config({
    input = {
        kb_layout  = "de",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",
        follow_mouse = 1,
        sensitivity = 0.40, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
        },
    },
})

-- Device specific input options
local Razer_sens = -0.46
hl.device({
    name        = "razer-razer-deathadder-v2-1",
    sensitivity = Razer_sens,
})
hl.device({
    name        = "razer-razer-deathadder-v2",
    sensitivity = Razer_sens,
})

-- https://wiki.hypr.land/Configuring/Variables/#gestures
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
-- HINWEIS: "swipe" als direction stand so in deiner .conf. Konnte in der Lua-API-Referenz
-- nicht 1:1 gegenprüfen (dort sind primär horizontal/vertical/left/right/up/down/any
-- dokumentiert) - falls Hyprland beim Start meckert, probier stattdessen direction="any".
hl.gesture({ fingers = 3, direction = "swipe", mods = "SUPER", action = "resize" })
hl.gesture({ fingers = 4, direction = "swipe", action = "move" })

-- Example per-device config (dieser Eintrag war unverändert aus der Beispiel-Config
-- übernommen, also vermutlich ein Platzhalter/Test-Device bei dir - ggf. löschen)
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------
-- See https://wiki.hypr.land/Configuring/Basics/Binds/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exit())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo()) -- dwindle
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
-- hl.bind(mainMod .. " + X", hl.dsp.layout("togglesplit")) -- dwindle (bei dir auskommentiert,
--                                                             und wirkungslos, da layout=master aktiv ist)
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd(browser))

-- Swaync keys
hl.bind("PRINT",          hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind("SHIFT + PRINT",  hl.dsp.exec_cmd("hyprshot -m region"))

-- Hyprlock keys
-- ACHTUNG: In deiner .conf stand "$SUPER_SHIFT" - diese Variable wurde nirgends definiert
-- (nur "$mainMod" existiert). Hyprland hätte das vermutlich als leeren String behandelt,
-- der Bind wäre also effektiv "L" ganz ohne Modifier gewesen. Ich hab's unten korrigiert
-- auf mainMod + SHIFT + L - wenn du wirklich nur "L" ohne Modifier wolltest, sag Bescheid.
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("hyprlock"))

-- Fullscreen mode
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ action = "toggle" }))

-- Move focus with mainMod + arrow keys or h,l,k,j
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Resize mainMod + ALT + arrow keys or h,l,k,j
hl.bind(mainMod .. " + ALT + left",  hl.dsp.window.resize({ x = -10, y = 0 }))
hl.bind(mainMod .. " + ALT + right", hl.dsp.window.resize({ x = 10,  y = 0 }))
hl.bind(mainMod .. " + ALT + up",    hl.dsp.window.resize({ x = 0,   y = -10 }))
hl.bind(mainMod .. " + ALT + down",  hl.dsp.window.resize({ x = 0,   y = 10 }))
hl.bind(mainMod .. " + ALT + h", hl.dsp.window.resize({ x = -10, y = 0 }))
hl.bind(mainMod .. " + ALT + l", hl.dsp.window.resize({ x = 10,  y = 0 }))
hl.bind(mainMod .. " + ALT + k", hl.dsp.window.resize({ x = 0,   y = -10 }))
hl.bind(mainMod .. " + ALT + j", hl.dsp.window.resize({ x = 0,   y = 10 }))

-- Switch workspaces with mainMod + [0-9], move active window with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Switch workspaces 11-20 with mainMod + CTRL + [0-9]
-- Move active window to workspace 11-20 with mainMod + SHIFT + CTRL + [0-9]
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + CTRL + " .. key,          hl.dsp.focus({ workspace = i + 10 }))
    hl.bind(mainMod .. " + SHIFT + CTRL + " .. key,  hl.dsp.window.move({ workspace = i + 10 }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl set 5%+"),                          { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl set 5%-"),                          { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------
-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- (die beiden exec-once von hier stehen jetzt oben im gemeinsamen AUTOSTART-Block)

hl.config({
    render = {
        direct_scanout = false,
    },
})

-- Erzwinge Floating für ProTanki (bei dir auskommentiert)
-- hl.window_rule({
--     name  = "float-protanki",
--     match = { title = "^(ProTanki)(.*)$" },
--     float = true,
-- })
-- hl.window_rule({
--     name  = "float-protanki-class",
--     match = { class = "^(protanki.exe)$" },
--     float = true,
-- })
-- -- Optional: Zentriere es
-- hl.window_rule({
--     name  = "center-protanki",
--     match = { class = "^(protanki.exe)$" },
--     center = true,
-- })
